### ISSUE TITLE
Title spelling mistake

### ISSUE THREAD

**Issue by zikalify** [standardebooks/benjamin-disraeli_sybil#1]
Just looked at this book on Gutenberg, Wikipedia, and Goodreads and they all spell it 'Sybil' but this github repo, the page on the site, and the book itself spells the title as 'Sibyl'. The blurb spells it 'Sybil', however. Is this an alternative spelling or a mistake?

**Comment by acabal** [comment]
@drgrigg can you take a look? The page scans you used also spell "Sybil": https://books.google.com.au/books?id=r99FAAAAcAAJ

**Comment by drgrigg** [comment]
Whoops! Definitely should be Sybil, my bad. Probably goes back to a typo when I ran create-draft. Will you fix it or will I fork and do a pull request?

**Comment by acabal** [comment]
I'll fix it

**Comment by acabal** [comment]
Fixed in 49413aff4e3d16ec6794cfc55039140267d1c6cf
